/*
**    KALC POS  - Professional Point of Sale
**
**    This file is part of KALC POS Version KALC V1.5.4
**
**    Copyright (c) 2015-2023 KALC & previous Openbravo POS related works   
**
**    https://www.KALC.co.uk
**   
**
*/


package ke.kalc.pos.sales.simple;

import java.awt.Dimension;
import javax.swing.JComponent;
import javax.swing.JPanel;
import ke.kalc.commons.dialogs.JAlertPane;
import ke.kalc.pos.forms.AppLocal;
import ke.kalc.pos.forms.AppView;
import ke.kalc.pos.sales.JTicketsBag;
import ke.kalc.pos.sales.TicketsEditor;
import ke.kalc.pos.ticket.TicketInfo;
import ke.kalc.globals.IconFactory;
import ke.kalc.pos.forms.KALCFonts;

/**
 *
 *
 */
public class JTicketsBagSimple extends JTicketsBag {

    /**
     * Creates new form JTicketsBagSimple
     *
     * @param app
     * @param panelticket
     */
    public JTicketsBagSimple(AppView app, TicketsEditor panelticket) {

        super(app, panelticket);

        initComponents();
    }

    /**
     *
     */
    public void activate() {

        m_panelticket.setActiveTicket(new TicketInfo(), null);

        // Authorization
        m_jDelTicket.setEnabled(m_App.getAppUserView().getUser().hasPermission("ke.kalc.pos.sales.JPanelTicketEdits"));

    }

    /**
     *
     * @return
     */
    public boolean deactivate() {
        m_panelticket.setActiveTicket(null, null);
        return true;
    }

    /**
     *
     */
    public void deleteTicket() {
        m_panelticket.setActiveTicket(new TicketInfo(), null);
    }

    /**
     *
     * @return
     */
    protected JComponent getBagComponent() {
        return this;
    }

    /**
     *
     * @return
     */
    protected JComponent getNullComponent() {
        return new JPanel();
    }

    public void deleteAllShared() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_jDelTicket = new javax.swing.JButton();

        setFont(KALCFonts.DEFAULTFONT.deriveFont(14f));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        m_jDelTicket.setIcon(IconFactory.getIcon("sale_delete.png"));
        m_jDelTicket.setFocusPainted(false);
        m_jDelTicket.setFocusable(false);
        m_jDelTicket.setMargin(new java.awt.Insets(0, 4, 0, 4));
        m_jDelTicket.setMaximumSize(new java.awt.Dimension(50, 40));
        m_jDelTicket.setMinimumSize(new java.awt.Dimension(50, 40));
        m_jDelTicket.setPreferredSize(new java.awt.Dimension(52, 40));
        m_jDelTicket.setRequestFocusEnabled(false);
        m_jDelTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jDelTicketActionPerformed(evt);
            }
        });
        add(m_jDelTicket);
    }// </editor-fold>//GEN-END:initComponents

    private void m_jDelTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jDelTicketActionPerformed
        if (JAlertPane.messageBox(JAlertPane.CONFIRMATION, AppLocal.getIntString("message.wannadelete"), 16, new Dimension(125, 50), JAlertPane.YES_NO_OPTION) == 5) {
            deleteTicket();
        }

    }//GEN-LAST:event_m_jDelTicketActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton m_jDelTicket;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getTicketByCode(String id) {

    }

}
