/*
**    KALC POS  - Open Source Point of Sale
**
**    This file is part of KALC POS Version KALC V1.5.4
**
**    Copyright (c) 2015-2023 KALC & previous Openbravo POS related works   
**
**    https://www.KALC.co.uk
**   
**    KALC POS is free software: you can redistribute it and/or modify
**    it under the terms of the GNU General Public License as published by
**    the Free Software Foundation, either version 3 of the License, or
**    (at your option) any later version.
**
**    KALC POS is distributed in the hope that it will be useful,
**    but WITHOUT ANY WARRANTY; without even the implied warranty of
**    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**    GNU General Public License for more details.
**
**    You should have received a copy of the GNU General Public License
**    along with KALC POS.  If not, see <http://www.gnu.org/licenses/>
**
*/


package uk.kalc.pos.payment;

import java.awt.BorderLayout;
import java.awt.Component;
import uk.kalc.globals.SystemProperty;
import uk.kalc.pos.customers.CustomerInfoExt;
import uk.kalc.pos.forms.AppLocal;
import uk.kalc.pos.forms.AppView;
import uk.kalc.pos.forms.KALCFonts;
import uk.kalc.pos.loyalty.LoyaltyCard;

public class JPaymentMagcard extends javax.swing.JPanel implements JPaymentInterface {

    private PaymentPanel m_cardpanel;
    private final PaymentGateway m_paymentgateway;
    private final JPaymentNotifier m_notifier;
    private String transaction;
    private String cardType = "magcard";

    public JPaymentMagcard(AppView app, JPaymentNotifier notifier, String cardType) {

        initComponents();
        this.cardType = cardType;
        m_notifier = notifier;
        m_paymentgateway = PaymentGatewayFac.getPaymentGateway();

        if (m_paymentgateway == null) {
            jlblMessage.setText(AppLocal.getIntString("message.nopaymentgateway"));
        } else {
            m_cardpanel = PaymentPanelFac.getPaymentPanel(SystemProperty.MAGREADER, notifier);
            add(m_cardpanel.getComponent(), BorderLayout.CENTER);
            jlblMessage.setText(null);
        }
    }

    public JPaymentMagcard(AppView app, JPaymentNotifier notifier) {
        initComponents();
        m_notifier = notifier;
        m_paymentgateway = PaymentGatewayFac.getPaymentGateway();

        if (m_paymentgateway == null) {
            jlblMessage.setText(AppLocal.getIntString("message.nopaymentgateway"));
        } else {
            m_cardpanel = PaymentPanelFac.getPaymentPanel(SystemProperty.MAGREADER, notifier);
            add(m_cardpanel.getComponent(), BorderLayout.CENTER);
            jlblMessage.setText(null);
        }
    }

    @Override
    public void activate(CustomerInfoExt customerext, double dTotal, String transID) {
        this.transaction = transID;

        if (m_cardpanel == null) {
            jlblMessage.setText(AppLocal.getIntString("message.nopaymentgateway"));
            m_notifier.setStatus(false, false);
        } else {
            jlblMessage.setText(null);
            m_cardpanel.activate(transaction, dTotal);
            // The cardpanel sets the status
        }
    }

    @Override
    public PaymentInfo executePayment() {
        jlblMessage.setText(null);
        PaymentInfoMagcard payinfo = m_cardpanel.getPaymentInfoMagcard();
        payinfo.setCardType(cardType);

        // Go to Payment gateway
        m_paymentgateway.execute(payinfo);

        revalidate();
        return payinfo;


    }

    @Override
    public Component getComponent() {
        return this;
    }

    @Override
    public Component getComponent(LoyaltyCard loyaltyCard) {
        return this;
    }

    /**
     *
     * @param transid
     */
    public void setTransaction(String transid) {
        transaction = transid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblMessage = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(300, 40));
        setPreferredSize(new java.awt.Dimension(300, 40));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setFont(KALCFonts.DEFAULTFONT.deriveFont(14f));
        jPanel1.setMinimumSize(new java.awt.Dimension(290, 35));
        jPanel1.setPreferredSize(new java.awt.Dimension(290, 35));

        jlblMessage.setFont(KALCFonts.DEFAULTFONT);
        jlblMessage.setText("jLabel1");
        jlblMessage.setMaximumSize(new java.awt.Dimension(46, 25));
        jlblMessage.setMinimumSize(new java.awt.Dimension(46, 25));
        jlblMessage.setPreferredSize(new java.awt.Dimension(46, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jlblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlblMessage;
    // End of variables declaration//GEN-END:variables

}
