/*
**    KALC POS  - Professional Point of Sale
**
**    This file is part of KALC POS Version KALC V1.5.4
**
**    Copyright (c) 2015-2023 KALC & previous KALC POS related works   
**
**    https://www.kalc.co.ke
**   
**
*/


package ke.kalc.pos.printer.screen;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.Rectangle;
import ke.kalc.pos.forms.KALCFonts;



class JTicketContainer extends javax.swing.JPanel {

    protected int H_GAP = 8;
    protected int V_GAP = 8;
    
    /** Creates new form JTicketContainer */
    public JTicketContainer() {
        initComponents();
        setLayout(null);
    }

    @Override
    public Dimension getPreferredSize() { 
        
        Insets ins = getInsets();
        int iMaxx = 0;
        int iMaxy = ins.top + V_GAP;
        int n = getComponentCount();
        for(int i = 0; i < n; i++) {
            Component comp = getComponent(i);
            Dimension dc = comp.getPreferredSize();
            if (dc.width > iMaxx) {
                iMaxx = dc.width;
            }
            iMaxy += V_GAP + dc.height;
        }

        return new Dimension(iMaxx + 2 * H_GAP + ins.left + ins.right, iMaxy + ins.bottom);
    }

    @Override
    public Dimension getMaximumSize() {
      return getPreferredSize();
    }

    @Override
    public Dimension getMinimumSize() {
      return getPreferredSize();
    }

    @Override
    public void doLayout() {
        Insets ins = getInsets();
        int x = ins.left + H_GAP;
        int y = ins.top + V_GAP;

        int n = getComponentCount();
        for(int i = 0; i < n; i++) {
            Component comp = getComponent(i);
            Dimension dc = comp.getPreferredSize();
            
            comp.setBounds(x, y, dc.width, dc.height);
            y += V_GAP + dc.height;
        }
    }
    
    public void addTicket(JTicket ticket) {
                
        add(ticket);
        
        doLayout();
        revalidate();
        scrollRectToVisible(new Rectangle(0, getPreferredSize().height - 1, 1, 1));
    }
    
    public void removeAllTickets() {
        
        removeAll();
        
        doLayout();
        revalidate();
        scrollRectToVisible(new Rectangle(0, 0, 1, 1));   
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFont(KALCFonts.DEFAULTFONT.deriveFont(14f)
        );
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
