/*
**    KALC POS  - Professional Point of Sale
**
**    This file is part of KALC POS Version KALC V1.5.4
**
**    Copyright (c) 2015-2023 KALC & previous Openbravo POS related works   
**
**    https://www.KALC.co.uk
**   
**
*/


package ke.kalc.pos.forms;

import javax.swing.JComponent;
import javax.swing.JPanel;
import ke.kalc.basic.BasicException;

public class JPanelNull extends JPanel implements JPanelView {

    /** Creates new form JPanelNull
     * @param oApp
     * @param o */
    public JPanelNull(AppView oApp, Object o) {
       
        initComponents ();
        if (o instanceof Exception) {
        }
        jtxtException.setText(o.toString());
    }

    /**
     *
     * @return
     */
    @Override
    public JComponent getComponent() {
        return this;
    }

    /**
     *
     * @return
     */
    @Override
    public String getTitle() {
        return null;
    }

    /**
     *
     * @throws BasicException
     */
    @Override
    public void activate() throws BasicException {
    }

    /**
     *
     * @return
     */
    @Override
    public boolean deactivate() {
        return true;
    }    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_jLabelError = new javax.swing.JLabel();
        jscrException = new javax.swing.JScrollPane();
        jtxtException = new javax.swing.JTextArea();

        setLayout(null);

        m_jLabelError.setFont(KALCFonts.DEFAULTFONTBOLD);
        m_jLabelError.setText(AppLocal.getIntString("label.loadError")); // NOI18N
        add(m_jLabelError);
        m_jLabelError.setBounds(30, 30, 490, 20);

        jtxtException.setEditable(false);
        jtxtException.setFont(KALCFonts.DEFAULTFONT.deriveFont(14f)
        );
        jtxtException.setLineWrap(true);
        jtxtException.setWrapStyleWord(true);
        jscrException.setViewportView(jtxtException);

        add(jscrException);
        jscrException.setBounds(30, 70, 550, 180);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jscrException;
    private javax.swing.JTextArea jtxtException;
    private javax.swing.JLabel m_jLabelError;
    // End of variables declaration//GEN-END:variables

}
