/*
**    KALC POS  - Professional Point of Sale
**
**    This file is part of KALC POS Version KALC V1.5.4
**
**    Copyright (c) 2015-2023 KALC & previous KALC POS related works   
**
**    https://www.kalc.co.ke
**   
**
 */
package ke.kalc.pos.forms;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.IOException;
import java.rmi.RemoteException;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import ke.kalc.globals.SystemProperty;
import ke.kalc.pos.instance.AppMessage;
import ke.kalc.pos.instance.InstanceManager;
import ke.kalc.pos.util.OSValidator;

public class JRootFrame extends javax.swing.JFrame implements AppMessage {

    private InstanceManager m_instmanager = null;
    private JRootApp m_rootapp;
    private AppProperties m_props;

    private OSValidator m_OS;

    public static JFrame PARENTFRAME;

    /**
     * Creates new form JRootFrame
     */
    public JRootFrame() {

        initComponents();
    }

    /**
     *
     * @param props
     */
    public void initFrame(AppProperties props) {

        m_OS = new OSValidator();
        m_props = props;
        m_rootapp = new JRootApp();
        int result = m_rootapp.initApp(m_props);
        if (result == m_rootapp.INIT_SUCCESS) {
//            if ("true".equals(AppConfigNew.getProperty("machine.uniqueinstance"))) {
//                try {
//                    m_instmanager = new InstanceManager(this);
//                } catch (RemoteException | AlreadyBoundException e) {
//                }
//            }
            add(m_rootapp, BorderLayout.CENTER);
            try {
                this.setIconImage(ImageIO.read(JRootFrame.class.getResourceAsStream("/uk/KALC/fixedimages/smllogo.png")));
            } catch (IOException e) {
            }
            setTitle(AppLocal.APP_NAME + " - V" + AppLocal.APP_VERSION + AppLocal.APP_DEMO);
            pack();
            setLocationRelativeTo(null);
            setVisible(true);
        } 

        PARENTFRAME = this;
        if (!SystemProperty.SCREENMODE.equals("fullscreen") && !SystemProperty.SCREENMODE.equals("kiosk - full screen")) {
            PARENTFRAME.setMinimumSize(new Dimension(1024, 738));
            PARENTFRAME.setSize(new Dimension(AppConfig.getInt("POSwidth", 1024), AppConfig.getInt("POSheight", 768)));
            if (AppConfig.getInt("POSx", -999) != -999) {
                PARENTFRAME.setLocation(AppConfig.getInt("POSx"), AppConfig.getInt("POSy"));
            }
        }
    }

    /**
     *
     * @throws RemoteException
     */
    @Override
    public void restoreWindow() throws RemoteException {
        java.awt.EventQueue.invokeLater(() -> {
            if (getExtendedState() == JFrame.ICONIFIED) {
                setExtendedState(JFrame.NORMAL);
            }
            requestFocus();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        m_rootapp.tryToClose();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
/*
    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        m_rootapp.tryToClose();
    }                                  
   
 */
