/*
**    KALC POS  - Professional Point of Sale
**
**    This file is part of KALC POS Version KALC V1.5.4
**
**    Copyright (c) 2015-2023 KALC & previous Openbravo POS related works   
**
**    https://www.KALC.co.uk
**   
**
*/


package ke.kalc.pos.sales;

import java.awt.Component;
import ke.kalc.editor.JEditorKeys;
import ke.kalc.pos.forms.KALCFonts;


public class JProductAttEditItem extends javax.swing.JPanel implements JProductAttEditI {

    private String attid;

    /** Creates new form JProductAttEditItem
     * @param attid
     * @param label
     * @param value
     * @param keys */
    public JProductAttEditItem(String attid, String label, String value, JEditorKeys keys) {

        this.attid = attid;

        initComponents();

        jLabel1.setText(label);

        jValue.addEditorKeys(keys);
        jValue.setText(value);
    }

    /**
     *
     */
    public void assignSelection() {
        jValue.activate();
    }

    /**
     *
     * @return
     */
    public String getAttribute() {
        return attid;
    }

    /**
     *
     * @return
     */
    public String getValue() {
        return jValue.getText();
    }

    /**
     *
     * @return
     */
    public Component getComponent() {
        return this;
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jValue = new ke.kalc.editor.JEditorString();

        jLabel1.setFont(KALCFonts.DEFAULTFONT.deriveFont(14f));
        jLabel1.setText("jLabel1");

        jValue.setFont(KALCFonts.DEFAULTFONT.deriveFont(14f)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jValue, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private ke.kalc.editor.JEditorString jValue;
    // End of variables declaration//GEN-END:variables

}
