/*
**    KALC POS  - Professional Point of Sale
**
**    This file is part of KALC POS Version KALC V1.5.4
**
**    Copyright (c) 2015-2023 KALC & previous KALC POS related works   
**
**    https://www.kalc.co.ke
**   
**
*/


package ke.kalc.pos.sales;

import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.List;
import ke.kalc.basic.BasicException;
import ke.kalc.pos.catalog.CatalogSelector;
import ke.kalc.pos.catalog.JCatalog;
import ke.kalc.pos.forms.AppView;
import ke.kalc.pos.datalogic.DataLogicSales;
import ke.kalc.pos.datalogic.DataLogicSystem;
import ke.kalc.pos.forms.KALCFonts;

/**
 *
 *   
 */
public class JTicketCatalogLines extends javax.swing.JPanel {
    
    private JRefundLines m_reflines;
    private CatalogSelector m_catalog;
    private String siteGuid;
    
    /** Creates new form JTicketCatalogLines
     * @param app
     * @param jTicketEdit
     * @param pricevisible
     * @param taxesincluded
     * @param width
     * @param height */
    public JTicketCatalogLines(AppView app, JPanelTicketEdits jTicketEdit, boolean pricevisible, boolean taxesincluded, int width, int height) {
        DataLogicSystem dlSystem = null;
        DataLogicSales dlSales = null;
        dlSystem = (DataLogicSystem) app.getBean("ke.kalc.pos.datalogic.DataLogicSystem");
        dlSales = (DataLogicSales) app.getBean("ke.kalc.pos.datalogic.DataLogicSales");
        
        
        siteGuid = dlSales.getSiteGUID();
        
        initComponents();
        
        m_reflines = new JRefundLines(dlSystem, dlSales, jTicketEdit);        
        add(m_reflines, "reflines");
        
        m_catalog = new JCatalog(dlSales,pricevisible, taxesincluded,siteGuid);
        m_catalog.getComponent().setPreferredSize(new Dimension(0, 245));
        // m_catalog.addActionListener(new CatalogListener());        
        add(m_catalog.getComponent(), "catalog");
    }
    
    /**
     *
     */
    public void showCatalog() {
        showView("catalog");
    }
    
    /**
     *
     * @throws BasicException
     */
    public void loadCatalog() throws BasicException {
        m_catalog.loadCatalog(siteGuid);
    }
    
    /**
     *
     * @param l
     */
    public void addActionListener(ActionListener l) {
        m_catalog.addActionListener(l);
    }

    /**
     *
     * @param l
     */
    public void removeActionListener(ActionListener l) {
        m_catalog.addActionListener(l);
    }
    
    /**
     *
     * @param aRefundLines
     */
    public void showRefundLines(List aRefundLines) {
        m_reflines.setLines(aRefundLines);
        showView("reflines");
    }   
    
    private void showView(String sView) {
        CardLayout cl = (CardLayout)(this.getLayout());
            cl.show(this, sView);       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setFont(KALCFonts.DEFAULTFONT);
        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
