/*
 **    KALC POS  - Professional Point of Sale
 **
 **    This file is part of KALC POS Version KALC V1.5.4
 **
 **    Copyright (c) 2015-2023 KALC & previous KALC POS related works   
 **
 **    https://www.kalc.co.ke
 **
 **
 */

package ke.kalc.pos.payment;

import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import ke.kalc.globals.SystemProperty;
import ke.kalc.pos.customers.CustomerInfoExt;
import ke.kalc.pos.forms.AppLocal;
import ke.kalc.pos.forms.AppView;
import ke.kalc.pos.forms.KALCFonts;
import ke.kalc.pos.loyalty.LoyaltyCard;
import java.awt.Window;
import javax.swing.SwingUtilities;
import javax.swing.JRootPane;
import javax.swing.JButton;
import javax.swing.JDialog;

/**
 * Mpesa Payment Implementation
 */
public class JPaymentMpesa extends javax.swing.JPanel implements JPaymentInterface {

    private JTextField m_jTransactionCode;
    private JLabel jlblMessage;
    private final JPaymentNotifier m_notifier;
    private String transaction;

    public JPaymentMpesa(AppView app, JPaymentNotifier notifier) {
        initComponents();
        m_notifier = notifier;
        jlblMessage.setText(null);
    }

    @Override
    public void activate(CustomerInfoExt customerext, double dTotal, String transID) {
        this.transaction = transID;
        m_jTransactionCode.setText("");
        jlblMessage.setText(null);
        m_notifier.setStatus(false, false); // Waiting for input
    }

    @Override
    public PaymentInfo executePayment() {
        String transactionCode = m_jTransactionCode.getText().trim();
        
        if (transactionCode.isEmpty()) {
            jlblMessage.setText(AppLocal.getIntString("message.mpesa.coderequired"));
            m_notifier.setStatus(false, false);
            return null;
        }
        
        // Validate transaction code format (typically alphanumeric, certain length)
        if (!transactionCode.matches("[A-Za-z0-9]{6,20}")) {
            jlblMessage.setText(AppLocal.getIntString("message.mpesa.invalidcode"));
            m_notifier.setStatus(false, false);
            return null;
        }
        
        // Create payment info for full amount
        double amount = m_notifier.getRemainingBalance();
        m_notifier.setStatus(true, true); // Success
        return new PaymentInfoCash_original(amount, amount);
    }

    @Override
    public Component getComponent() {
        return this;
    }

    @Override
    public Component getComponent(LoyaltyCard loyaltyCard) {
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        JPanel jPanel1 = new JPanel();
        jlblMessage = new JLabel();
        m_jTransactionCode = new JTextField();

        setLayout(new BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel1.add(new JLabel(AppLocal.getIntString("label.mpesa.transactioncode") + ":"));
        jPanel1.add(m_jTransactionCode);
        m_jTransactionCode.setColumns(15);

        add(jPanel1, BorderLayout.NORTH);
        add(jlblMessage, BorderLayout.CENTER);

        // Add Enter key listener to process payment
        m_jTransactionCode.addActionListener(e -> {
            java.awt.Window window = SwingUtilities.getWindowAncestor(JPaymentMpesa.this);
            if (window instanceof javax.swing.JDialog) {
                javax.swing.JRootPane rp = ((javax.swing.JDialog) window).getRootPane();
                javax.swing.JButton defaultButton = rp.getDefaultButton();
                if (defaultButton != null) {
                    defaultButton.doClick();
                }
            }
        });
    }// </editor-fold>
}